# Generated by Django 4.2.27 on 2025-12-28 14:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the place (e.g., restaurant name, shop name)', max_length=255)),
                ('address', models.TextField(help_text='Full address of the place')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'db_table': 'places',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (worst) to 5 (best)', validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1'), django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5')])),
                ('text', models.TextField(blank=True, default='', help_text='Optional review text/comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(help_text='Place being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.place')),
                ('user', models.ForeignKey(help_text='User who wrote this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='place_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_place_name_address'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'place'], name='review_user_place_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='review_created_at_idx'),
        ),
    ]
